Internatinalize VirtualCloneDrive code.

diff --git a/winetricks b/winetricks
--- a/winetricks
+++ b/winetricks
@@ -2774,13 +2774,9 @@ load_vcdmount()
     # http://www.slysoft.com/en/virtual-clonedrive.html
     # FIXME: actually install it here
 
-    # Locate vcdmount.exe.   FIXME: internationalize this.
-    for PROGRAMFILES in "c:/Program Files (x86)" "c:/Program Files"
-    do
-        test -d "$PROGRAMFILES" && break
-    done
-    VCD_DIR="$PROGRAMFILES/Elaborate Bytes/VirtualCloneDrive"
-    if test ! -x "$VCD_DIR/vcdmount.exe" 
+    # Locate vcdmount.exe.
+    VCD_DIR="Elaborate Bytes/VirtualCloneDrive"
+    if test ! -x "$programfilesdir_unix/$VCD_DIR/vcdmount.exe" && test ! -x "$programfilesdir_x86_unix/$VCD_DIR/vcdmount.exe" 
     then
         warn "Installing Virtual CloneDrive"
         download . http://static.slysoft.com/SetupVirtualCloneDrive.exe
@@ -2789,6 +2785,15 @@ load_vcdmount()
         cd "$WINETRICKS_CACHE"
         cmd /c SetupVirtualCloneDrive.exe
         cd "$olddir"
+    fi
+    if test -x "$programfilesdir_unix/$VCD_DIR/vcdmount.exe"
+    then
+        VCD_DIR="$programfilesdir_unix/$VCD_DIR" 
+    elif test -x "$programfilesdir_x86_unix/$VCD_DIR/vcdmount.exe" 
+    then
+        VCD_DIR="$programfilesdir_x86_unix/$VCD_DIR" 
+    else
+        die "can't find Virtual CloneDrive?"
     fi
 
     # FIXME: Use WMI to locate the drive named
@@ -3275,6 +3280,15 @@ test x"$programfilesdir_win" != x || die "$WINE cmd.exe /c echo '%ProgramFiles%'
 programfilesdir_unix="`unset WINEDEBUG; $XXXPATH -u "$programfilesdir_win" | tr -d '\015' `"
 test x"$programfilesdir_unix" != x || die "winepath -u $programfilesdir_win returned empty string"
 winetricks_tmp_win="`$XXXPATH -w "$WINETRICKS_TMP"`"
+
+# 64 bit windows has a second directory for program files
+programfilesdir_x86_win="${programfilesdir_win} (x86)"
+programfilesdir_x86_unix="${programfilesdir_unix} (x86)"
+if ! test -d "$programfilesdir_x86_unix"
+then
+    programfilesdir_x86_win="${programfilesdir_win}"
+    programfilesdir_x86_unix="${programfilesdir_unix}"
+fi
 
 # (Fixme: get fonts path from SHGetFolderPath
 # See also http://blogs.msdn.com/oldnewthing/archive/2003/11/03/55532.aspx)
