wisotool: download no longer leaves size zero files laying around upon failure.  Also remove sourceforge URLs, since they're not used.

diff --git a/wisotool b/wisotool
--- a/wisotool
+++ b/wisotool
@@ -85,15 +85,6 @@ ISO_MOUNT_ROOT=/mnt/wisotool
 
 WINDIR="$DRIVE_C/windows"
 
-# Which sourceforge mirror to use.  Rotate based on time, since
-# their mirror picker sometimes persistantly sends you to a broken
-# mirror.
-case `date +%S` in
-*[01]) SOURCEFORGE=http://internap.dl.sourceforge.net/sourceforge ;;
-*[23]) SOURCEFORGE=http://easynews.dl.sourceforge.net/sourceforge ;;
-*)     SOURCEFORGE=http://downloads.sourceforge.net;;
-esac
-
 #---- Functions -------------------------------------------------
 
 # Detect which sudo to use
@@ -379,6 +370,7 @@ download() {
         # On Mac, 'which' doesn't return good exit status
         # Need to jam in --header "Accept-Encoding: gzip,deflate" else
         # redhat.com decompresses liberation-fonts.tar.gz!
+        echo Downloading $2
         if [ -x "`which wget 2>/dev/null`" ]
         then
            # Use -nd to insulate ourselves from people who set -x in WGETRC
@@ -388,11 +380,16 @@ download() {
            # close the connection unless you tell it to (control-C or closing
            # the socket)
            # Disable retries for gog.com (which requires higher level retries)
-           try wget -O "$file" -nd -c --read-timeout=300 --tries=1 --retry-connrefused --header "Accept-Encoding: gzip,deflate" ${5:+--load-cookies "$5"} "$2"
+           wget -O "$file" -nd -c --read-timeout=300 --tries=1 --retry-connrefused --header "Accept-Encoding: gzip,deflate" ${5:+--load-cookies "$5"} "$2"
         else
            # curl doesn't get filename from the location given by the server!
            # fortunately, we know it
-           try curl -L -o "$file" -C - --header "Accept-Encoding: gzip,deflate" ${5:+--cookie "$5"} "$2"
+           curl -L -o "$file" -C - --header "Accept-Encoding: gzip,deflate" ${5:+--cookie "$5"} "$2"
+        fi
+        if test $? != 0
+        then
+            test -f "$file" && rm "$file"
+            die "Downloading $2 failed"
         fi
         # Need to decompress .exe's that are compressed, else cygwin fails
         # Only affects cygwin, so don't barf if 'file' not installed
