Support vc2005trial under Windows, kind of.

diff --git a/trunk/winetricks b/trunk/winetricks
--- a/trunk/winetricks
+++ b/trunk/winetricks
@@ -2157,6 +2157,85 @@ load_vc2005expresssp1()
     try $WINE "$WINETRICKS_CACHE"/vc2005express/VS80sp1-KB926748-X86-INTL.exe
 }
 
+load_vcdmount()
+{
+    # Call only on real Windows.
+    # Sets VCDMOUNT and ISO_MOUNT_ROOT
+
+    # The only free mount tool I know for Windows Vista is Virtual CloneDrive,
+    # which can be downloaded at 
+    # http://www.slysoft.com/en/virtual-clonedrive.html
+    # FIXME: actually install it here
+
+    # Locate vcdmount.exe.   FIXME: internationalize this.
+    for PROGRAMFILES in "c:/Program Files (x86)" "c:/Program Files"
+    do
+        test -d "$PROGRAMFILES" && break
+    done
+    VCDMOUNT="$PROGRAMFILES/Elaborate Bytes/VirtualCloneDrive/vcdmount.exe"
+    test -x "$VCDMOUNT" || die "Please install Virtual CloneDrive"
+
+    # Find a drive letter (really, VCD has a few in mind, on my system
+    # it starts at f.  FIXME: figure out more portable way to do this.)
+    for letter in f g h i j k l m n o p q r s t u v w x y
+    do
+        ISO_MOUNT_ROOT=/cygdrive/$letter
+        test -d $ISO_MOUNT_ROOT || break
+    done
+    test -d $ISO_MOUNT_ROOT && die "cannot find a free drive letter"
+}
+
+iso_mount()
+{
+    my_img="$1"
+
+    if test "$WINE" = ""
+    then
+        load_vcdmount
+        my_img_win="`$XXXPATH -w $my_img`"
+        try "$VCDMOUNT" /l=$letter "$my_img_win"
+        while ! test -d "$ISO_MOUNT_ROOT"
+        do
+            echo "Waiting for mount to finish"
+            sleep 1
+        done
+    else 
+        # Linux
+        ISO_MOUNT_ROOT=/mnt/winetricks
+        case "$GUI-$DE" in
+        gnome) 
+          1-gksudo "mkdir -p $ISO_MOUNT_ROOT"
+          1-gksudo "mount -o ro,loop $my_img $ISO_MOUNT_ROOT"
+          ;;
+        *)
+          sudo mkdir -p $ISO_MOUNT_ROOT
+          sudo mount -o ro,loop "$my_img" $ISO_MOUNT_ROOT
+          ;;
+        esac
+    fi
+}
+
+iso_umount()
+{
+    if test "$WINE" = ""
+    then
+        # Windows
+        load_vcdmount
+        "$VCDMOUNT" /u
+    else
+        case "$GUI-$DE" in
+        gnome) 
+          1-gksudo "umount $ISO_MOUNT_ROOT"
+          1-gksudo "rm -rf $ISO_MOUNT_ROOT"
+          ;;
+        *)
+          sudo umount $ISO_MOUNT_ROOT
+          sudo rm -rf $ISO_MOUNT_ROOT
+          ;;
+        esac
+    fi
+}
+
 #----------------------------------------------------------------
 
 load_vc2005trial()
@@ -2166,21 +2245,13 @@ load_vc2005trial()
     load_msxml6
 
     echo "Downloading/checksumming Visual C++ 2005 Trial.  This will take some time!"
-    download vc2005trial http://download.microsoft.com/download/6/f/5/6f5f7a01-50bb-422d-8742-c099c8896969/En_vs_2005_vsts_180_Trial.img 0204bce1dacfa15b45052647139b35e31e9e36ee
+    download vc2005trial http://download.microsoft.com/download/6/f/5/6f5f7a01-50bb-422d-8742-c099c8896969/En_vs_2005_vsts_180_Trial.img f66ae07618d67e693ca0524d3582208c20e07823
 
-    # FIXME: linux-specific
-    IMG="$WINETRICKS_CACHE"/vc2005trial/En_vs_2005_vsts_180_Trial.img
-    warn "Mounting Visual Studio 2005 Trial disk image..."
-    case "$GUI-$DE" in
-    gnome) 
-      1-gksudo "mkdir -p /mnt/winetricks/vc2005trial"
-      1-gksudo "mount -o ro,loop $IMG /mnt/winetricks/vc2005trial"
-      ;;
-    *)
-      sudo mkdir -p /mnt/winetricks/vc2005trial
-      sudo mount -o ro,loop $IMG /mnt/winetricks/vc2005trial
-      ;;
-    esac
+    iso_umount
+    iso_mount "$WINETRICKS_CACHE"/vc2005trial/En_vs_2005_vsts_180_Trial.img
+
+    # FIXME: do this right
+    rm -f /cygdrive/c/Users/$USER/AppData/local/temp/dd_vsinstall80.txt
 
     if false && [ $WINETRICKS_QUIET ]
     then
@@ -2188,24 +2259,28 @@ load_vc2005trial()
       # See also http://support.microsoft.com/?kbid=913445
       die "not implemented yet"
     else
-      try $WINE /mnt/winetricks/vc2005trial/vs/setup/setup.exe
-      while ps | grep -q setup.exe
-      do
-          sleep 10
-          echo waiting for setup to finish
-      done
+      cd $ISO_MOUNT_ROOT/vs/setup
+      try $WINE setup.exe
+
+      # FIXME: unify these and make the windows one right
+      if test "$WINE" = ""
+      then
+          while ! tr -d '\000' < /cygdrive/c/Users/$USER/AppData/local/temp/dd_vsinstall80.txt | grep End_Session
+          do
+              sleep 10
+              echo waiting for setup to finish
+          done
+      else
+          while ps $psargs | grep -q setup.exe
+          do
+              sleep 10
+              echo waiting for setup to finish
+          done
+      fi
+      cd "$olddir"
     fi
 
-    case "$GUI-$DE" in
-    gnome) 
-      1-gksudo "umount /mnt/winetricks/vc2005trial"
-      1-gksudo "rm -rf /mnt/winetricks"
-      ;;
-    *)
-      sudo umount /mnt/winetricks/vc2005trial
-      sudo rm -rf /mnt/winetricks
-      ;;
-    esac
+    iso_umount
 }
 
 #----------------------------------------------------------------
