winetrickstest: for dotnet/mono, try running a real dotnet app (if mono-gmcs is available to compile one)

diff --git a/trunk/winetrickstest b/trunk/winetrickstest
--- a/trunk/winetrickstest
+++ b/trunk/winetrickstest
@@ -133,6 +133,31 @@ do
     sh winetricks  -q -v $verb
 done
 
+# Test dotnet/etc. a bit more extensively:
+if [ ! -x "`which gmcs`" ]
+then
+    echo "gmcs not found, please install it to test dotnet/mono"
+    echo "e.g., sudo apt-get install mono-gmcs"
+else
+    cat > dotnet_test.c << __EOF__
+using System; class ExampleClass { static void Main(){Console.WriteLine("Dotnet works!");} }
+__EOF__
+    for verb in \
+        dotnet20 \
+        mono20 \
+        mono22 \
+        mono24 \
+        mono26 \ 
+    do
+        wineserver -k || true
+        rm -rf $WINEPREFIX
+        sh winetricks  -q -v $verb
+        # wget http://winezeug.googlecode.com/svn/trunk/winetricks_files/dotnettest.exe
+        wine dotnet_test.exe | grep "Dotnet works!"
+    done
+    rm dotnet_test.{c,exe}
+fi
+
 # Known to have problems
 
 if [ "$1" = "--all" ]
