- rotate sourceforge mirrors to avoid getting stuck on bad one - cope with users who rename c:/windows/Fonts to c:/windows/fonts - more conservative advice on sha1sum mismatches - handle bad exit status from /usr/bin/which on mac - cope with redhat.com sending decompressed files - use win2K when installing directx so it installs more stuff

diff --git a/trunk/winetricks b/trunk/winetricks
--- a/trunk/winetricks
+++ b/trunk/winetricks
@@ -20,9 +20,18 @@ WINETRICKS_TMP="$WINEPREFIX"/drive_c/winetrickstmp
 mkdir -p "$WINETRICKS_TMP"
 WINETRICKS_TMP_WIN='c:\winetrickstmp'
 
+# Which sourceforge mirror to use.  Rotate based on time, since 
+# their mirror picker sometimes persistantly sends you to a broken
+# mirror.
+case `date +%S` in
+*[01]) SOURCEFORGE=http://internap.dl.sourceforge.net/sourceforge ;;
+*[23]) SOURCEFORGE=http://easynews.dl.sourceforge.net/sourceforge ;;
+*)     SOURCEFORGE=http://downloads.sourceforge.net;;
+esac
+
 case "$1" in
 -V|--version) 
-  echo "Winetricks version 20080522.  (C) Dan Kegel.  LGPL."
+  echo "Winetricks version 20080523.  (C) Dan Kegel.  LGPL."
   exit 0
   ;;
 esac
@@ -234,8 +243,16 @@ rm -rf "$WINETRICKS_TMP"/*
 programfilesdir_win=`$WINE cmd.exe /c echo "%ProgramFiles%"`
 programfilesdir_unix=`$WINE winepath -u "$programfilesdir_win"`
 
+# Did the user rename Fonts to fonts?
+if ! test -d "$WINEPREFIX"/drive_c/windows/Fonts && test -d "$WINEPREFIX"/drive_c/windows/fonts 
+then
+    winefontsdir="$WINEPREFIX"/drive_c/windows/fonts
+else
+    winefontsdir="$WINEPREFIX"/drive_c/windows/Fonts
+fi
+
 # Mac folks tend to not have sha1sum, but we can make do with openssl
-if which sha1sum > /dev/null
+if [ -x "`which sha1sum`" ]
 then
    SHA1SUM="sha1sum"
 else
@@ -273,7 +290,7 @@ verify_sha1sum() {
     gotsum=`$SHA1SUM < $file | sed 's/ .*//'`
     if [ "$gotsum"x != "$wantsum"x ]
     then
-       die "sha1sum mismatch!  Delete $file and try again."
+       die "sha1sum mismatch!  Rename $file and try again."
     fi
 }
 
@@ -293,7 +310,10 @@ download() {
     then
         cd "$cache"
         # Mac folks tend to have curl rather than wget
-        if which wget > /dev/null
+        # On Mac, 'which' doesn't return good exit status
+        # Need to jam in --header "Accept-Encoding: gzip,deflate" else
+        # redhat.com decompresses liberation-fonts.tar.gz!
+        if [ -x "`which wget`" ]
         then
            # Use -nd to insulate ourselves from people who set -x in WGETRC
            # [*] --retry-connrefused works around the broken sf.net mirroring
@@ -301,11 +321,11 @@ download() {
            # [*] --read-timeout is useful on the adobe server that doesn't
            # close the connection unless you tell it to (control-C or closing
            # the socket)
-           try wget -nd -c --read-timeout=300 --retry-connrefused "$2"
+           try wget -nd -c --read-timeout=300 --retry-connrefused --header "Accept-Encoding: gzip,deflate" "$2"
         else
            # curl doesn't get filename from the location given by the server!
            # fortunately, we know it
-           try curl -L -o $file -C - "$2"
+           try curl -L -o $file -C - --header "Accept-Encoding: gzip,deflate" "$2"
         fi
         cd $olddir
     fi
@@ -450,17 +470,17 @@ load_corefonts() {
     # Added More Fonts (see msttcorefonts)
     # [*] Pointed download locations to sites that actually contained the
     # fonts to download (as of 04-03-2008)			    
-    #download . http://internap.dl.sourceforge.net/sourceforge/corefonts/andale32.exe c4db8cbe42c566d12468f5fdad38c43721844c69
-    download . http://easynews.dl.sourceforge.net/sourceforge/corefonts/arial32.exe 6d75f8436f39ab2da5c31ce651b7443b4ad2916e
-    download . http://internap.dl.sourceforge.net/sourceforge/corefonts/arialb32.exe d45cdab84b7f4c1efd6d1b369f50ed0390e3d344
-    download . http://easynews.dl.sourceforge.net/sourceforge/corefonts/comic32.exe 2371d0327683dcc5ec1684fe7c275a8de1ef9a51
-    download . http://internap.dl.sourceforge.net/sourceforge/corefonts/courie32.exe 06a745023c034f88b4135f5e294fece1a3c1b057
-    download . http://easynews.dl.sourceforge.net/sourceforge/corefonts/georgi32.exe 90e4070cb356f1d811acb943080bf97e419a8f1e
-    download . http://internap.dl.sourceforge.net/sourceforge/corefonts/impact32.exe 86b34d650cfbbe5d3512d49d2545f7509a55aad2
-    download . http://easynews.dl.sourceforge.net/sourceforge/corefonts/times32.exe 20b79e65cdef4e2d7195f84da202499e3aa83060
-    download . http://internap.dl.sourceforge.net/sourceforge/corefonts/trebuc32.exe 50aab0988423efcc9cf21fac7d64d534d6d0a34a
-    download . http://internap.dl.sourceforge.net/sourceforge/corefonts/verdan32.exe f5b93cedf500edc67502f116578123618c64a42a
-    download . http://easynews.dl.sourceforge.net/sourceforge/corefonts/webdin32.exe 2fb4a42c53e50bc70707a7b3c57baf62ba58398f
+    #download . $SOURCEFORGE/corefonts/andale32.exe c4db8cbe42c566d12468f5fdad38c43721844c69
+    download . $SOURCEFORGE/corefonts/arial32.exe 6d75f8436f39ab2da5c31ce651b7443b4ad2916e
+    download . $SOURCEFORGE/corefonts/arialb32.exe d45cdab84b7f4c1efd6d1b369f50ed0390e3d344
+    download . $SOURCEFORGE/corefonts/comic32.exe 2371d0327683dcc5ec1684fe7c275a8de1ef9a51
+    download . $SOURCEFORGE/corefonts/courie32.exe 06a745023c034f88b4135f5e294fece1a3c1b057
+    download . $SOURCEFORGE/corefonts/georgi32.exe 90e4070cb356f1d811acb943080bf97e419a8f1e
+    download . $SOURCEFORGE/corefonts/impact32.exe 86b34d650cfbbe5d3512d49d2545f7509a55aad2
+    download . $SOURCEFORGE/corefonts/times32.exe 20b79e65cdef4e2d7195f84da202499e3aa83060
+    download . $SOURCEFORGE/corefonts/trebuc32.exe 50aab0988423efcc9cf21fac7d64d534d6d0a34a
+    download . $SOURCEFORGE/corefonts/verdan32.exe f5b93cedf500edc67502f116578123618c64a42a
+    download . $SOURCEFORGE/corefonts/webdin32.exe 2fb4a42c53e50bc70707a7b3c57baf62ba58398f
 
     # Natively installed versions of these fonts will cause the installers
     # to exit silently. Because there are apps out there that depend on the
@@ -474,62 +494,62 @@ load_corefonts() {
     test x"$WINETRICKS_QUIET" = x"" || try $WINE "$WINETRICKS_CACHE"/arial32.exe $WINETRICKS_QUIET
 
     try cabextract -q --directory="$WINETRICKS_TMP" "$WINETRICKS_CACHE"/arial32.exe
-    try cp -f "$WINETRICKS_TMP"/Arial*.TTF "$WINEPREFIX"/drive_c/windows/Fonts
+    try cp -f "$WINETRICKS_TMP"/Arial*.TTF "$winefontsdir"
     register_font Arial.TTF "Arial (TrueType)"
     register_font Arialbd.TTF "Arial Bold (TrueType)"
     register_font Arialbi.TTF "Arial Bold Italic (TrueType)"
     register_font Ariali.TTF "Arial Italic (TrueType)"
 
     try cabextract -q --directory="$WINETRICKS_TMP" "$WINETRICKS_CACHE"/arialb32.exe
-    try cp -f "$WINETRICKS_TMP"/AriBlk.TTF "$WINEPREFIX"/drive_c/windows/Fonts
+    try cp -f "$WINETRICKS_TMP"/AriBlk.TTF "$winefontsdir"
     register_font AriBlk.TTF "Arial Black (TrueType)"
 
     try cabextract -q --directory="$WINETRICKS_TMP" "$WINETRICKS_CACHE"/comic32.exe
-    try cp -f "$WINETRICKS_TMP"/Comic*.TTF "$WINEPREFIX"/drive_c/windows/Fonts
+    try cp -f "$WINETRICKS_TMP"/Comic*.TTF "$winefontsdir"
     register_font Comic.TTF "Comic Sans MS (TrueType)"
     register_font Comicbd.TTF "Comic Sans MS Bold (TrueType)"
 
     try cabextract -q --directory="$WINETRICKS_TMP" "$WINETRICKS_CACHE"/courie32.exe
-    try cp -f "$WINETRICKS_TMP"/cour*.ttf "$WINEPREFIX"/drive_c/windows/Fonts
+    try cp -f "$WINETRICKS_TMP"/cour*.ttf "$winefontsdir"
     register_font Cour.TTF "Courier New (TrueType)"
     register_font CourBD.TTF "Courier New Bold (TrueType)"
     register_font CourBI.TTF "Courier New Bold Italic (TrueType)"
     register_font Couri.TTF "Courier New Italic (TrueType)"
 
     try cabextract -q --directory="$WINETRICKS_TMP" "$WINETRICKS_CACHE"/georgi32.exe
-    try cp -f "$WINETRICKS_TMP"/Georgia*.TTF "$WINEPREFIX"/drive_c/windows/Fonts
+    try cp -f "$WINETRICKS_TMP"/Georgia*.TTF "$winefontsdir"
     register_font Georgia.TTF "Georgia (TrueType)"
     register_font Georgiab.TTF "Georgia Bold (TrueType)"
     register_font Georgiaz.TTF "Georgia Bold Italic (TrueType)"
     register_font Georgiai.TTF "Georgia Italic (TrueType)"
 
     try cabextract -q --directory="$WINETRICKS_TMP" "$WINETRICKS_CACHE"/impact32.exe
-    try cp -f "$WINETRICKS_TMP"/Impact.TTF "$WINEPREFIX"/drive_c/windows/Fonts
+    try cp -f "$WINETRICKS_TMP"/Impact.TTF "$winefontsdir"
     register_font Impact.TTF "Impact (TrueType)"
 
     try cabextract -q --directory="$WINETRICKS_TMP" "$WINETRICKS_CACHE"/times32.exe
-    try cp -f "$WINETRICKS_TMP"/Times*.TTF "$WINEPREFIX"/drive_c/windows/Fonts
+    try cp -f "$WINETRICKS_TMP"/Times*.TTF "$winefontsdir"
     register_font Times.TTF "Times New Roman (TrueType)"
     register_font Timesbd.TTF "Times New Roman Bold (TrueType)"
     register_font Timesbi.TTF "Times New Roman Bold Italic (TrueType)"
     register_font Timesi.TTF "Times New Roman Italic (TrueType)"
 
     try cabextract -q --directory="$WINETRICKS_TMP" "$WINETRICKS_CACHE"/trebuc32.exe
-    try cp -f "$WINETRICKS_TMP"/trebuc*.ttf "$WINEPREFIX"/drive_c/windows/Fonts
+    try cp -f "$WINETRICKS_TMP"/trebuc*.ttf "$winefontsdir"
     register_font Trebuc.TTF "Trebucet MS (TrueType)"
     register_font Trebucbd.TTF "Trebucet MS Bold (TrueType)"
     register_font Trebucbi.TTF "Trebucet MS Bold Italic (TrueType)"
     register_font Trebucit.TTF "Trebucet MS Italic (TrueType)"
 
     try cabextract -q --directory="$WINETRICKS_TMP" "$WINETRICKS_CACHE"/verdan32.exe
-    try cp -f "$WINETRICKS_TMP"/Verdana*.TTF "$WINEPREFIX"/drive_c/windows/Fonts
+    try cp -f "$WINETRICKS_TMP"/Verdana*.TTF "$winefontsdir"
     register_font Verdana.TTF "Verdana (TrueType)"
     register_font Verdanab.TTF "Verdana Bold (TrueType)"
     register_font Verdanaz.TTF "Verdana Bold Italic (TrueType)"
     register_font Verdanai.TTF "Verdana Italic (TrueType)"
 
     try cabextract -q --directory="$WINETRICKS_TMP" "$WINETRICKS_CACHE"/webdin32.exe
-    try cp -f "$WINETRICKS_TMP"/Webdings.TTF "$WINEPREFIX"/drive_c/windows/Fonts
+    try cp -f "$WINETRICKS_TMP"/Webdings.TTF "$winefontsdir"
     register_font Webdings.TTF "Webdings (TrueType)"
 }
 
@@ -546,8 +566,10 @@ load_directx9() {
     # For #3, I have no idea which DLLs don't register themselves well yet,
     # so I'm just listing a few of the basic ones.  Let's whittle that
     # list down as soon as we can.  
+    set_winver win2k
     WINEDLLOVERRIDES="wintrust=b,mscoree=,ddraw,d3d8,d3d9,dsound,dinput=n" \
        try $WINE "$WINETRICKS_CACHE"/directx_mar2008_redist.exe /t:"$WINETRICKS_TMP_WIN" $WINETRICKS_QUIET
+    unset_winver
 }
 
 #----------------------------------------------------------------
@@ -668,7 +690,7 @@ _EOF_
 
 load_ffdshow() {
     # ffdshow
-    download . http://downloads.sourceforge.net/ffdshow-tryout/ffdshow_beta4a_rev1723_20071224_clsid.exe 6e018139c3ed4800aa3580267d1da47fa936a82a
+    download . $SOURCEFORGE/ffdshow-tryout/ffdshow_beta4a_rev1723_20071224_clsid.exe 6e018139c3ed4800aa3580267d1da47fa936a82a
     try $WINE "$WINETRICKS_CACHE"/ffdshow_beta4a_rev1723_20071224_clsid.exe $WINETRICKS_SILENT
 }
 
@@ -698,7 +720,7 @@ load_fontfix() {
             download . http://apt.debian.org.tw/pool/t/ttf-arphic-ukai/ttf-arphic-ukai_0.1.20060108.orig.tar.gz 46cc7b67b6117a7e161c1a573502c0bf2b09cbdc  
             cd "$WINETRICKS_TMP/"
 	    tar -xzf "$WINETRICKS_CACHE/ttf-arphic-ukai_0.1.20060108.orig.tar.gz"
-	    try mv ttf-arphic-ukai-0.1.20060108/*.ttf "$WINEPREFIX/drive_c/windows/Fonts"
+	    try mv ttf-arphic-ukai-0.1.20060108/*.ttf "$winefontsdir""
             cd "$olddir"
         fi
     fi
@@ -711,7 +733,7 @@ load_fontfix() {
             download . http://apt.debian.org.tw/pool/t/ttf-arphic-uming/ttf-arphic-uming_0.1.20060108.orig.tar.gz ec34aeb240fcce09d25fce2fbe5e5b6f358c2f24  
             cd "$WINETRICKS_TMP/"
 	    tar -xzf "$WINETRICKS_CACHE/ttf-arphic-uming_0.1.20060108.orig.tar.gz"
-	    try mv ttf-arphic-uming-0.1.20060108/*.ttf "$WINEPREFIX/drive_c/windows/Fonts"
+	    try mv ttf-arphic-uming-0.1.20060108/*.ttf "$winefontsdir""
             cd "$olddir"
         fi
     fi
@@ -797,7 +819,7 @@ load_liberation() {
     download . http://www.redhat.com/f/fonts/liberation-fonts.tar.gz 38276ab5e4322e131217d26f193bfce396195c0a
     # Fixme: get fonts path from SHGetFolderPath
     # see also http://blogs.msdn.com/oldnewthing/archive/2003/11/03/55532.aspx
-    tar --wildcards -C "$WINEPREFIX"/drive_c/windows/Fonts -xvzf "$WINETRICKS_CACHE"/liberation-fonts.tar.gz '*.ttf'
+    tar --wildcards -C "$winefontsdir" -xvzf "$WINETRICKS_CACHE"/liberation-fonts.tar.gz '*.ttf'
 }
 
 #----------------------------------------------------------------
@@ -1014,12 +1036,13 @@ load_riched30() {
 
 load_tahoma() {
     # The tahoma font is needed by e.g. Steam
-    download . http://downloads.sourceforge.net/corefonts/wd97vwr32.exe 8edf758f92513094a94e50b7826cd6f2b7696b8c
+    download . $SOURCEFORGE/corefonts/wd97vwr32.exe 8edf758f92513094a94e50b7826cd6f2b7696b8c
     try cabextract --directory="$WINETRICKS_TMP" "$WINETRICKS_CACHE"/wd97vwr32.exe
     try cabextract --directory="$WINETRICKS_TMP" $WINETRICKS_TMP/Viewer1.cab
     # Fixme: get fonts path from SHGetFolderPath
     # see also http://blogs.msdn.com/oldnewthing/archive/2003/11/03/55532.aspx
-    try cp -f "$WINETRICKS_TMP"/tahoma.ttf "$WINEPREFIX"/drive_c/windows/Fonts/tahoma.ttf
+    try cp -f "$WINETRICKS_TMP"/tahoma.ttf "$winefontsdir"/tahoma.ttf
+    chmod +w "$winefontsdir"/tahoma.ttf
     rm -rf "$WINETRICKS_TMP"/*
 }
 
@@ -1103,7 +1126,7 @@ load_vcrun2003() {
     # Load the Visual C++ 2003 runtime libraries
     # Sadly, I know of no Microsoft URL for these
     echo "Installing BZFlag (which comes with the Visual C++ 2003 runtimes)"
-    download . http://dl.sourceforge.net/bzflag/BZEditW32_1.6.5_Installer.exe bdd1b32c4202fd77e6513fd507c8236888b09121
+    download . $SOURCEFORGE/bzflag/BZEditW32_1.6.5_Installer.exe bdd1b32c4202fd77e6513fd507c8236888b09121
     try $WINE "$WINETRICKS_CACHE"/BZEditW32_1.6.5_Installer.exe $WINETRICKS_S
     cp "$programfilesdir_unix/BZEdit1.6.5"/m*71* "$WINEPREFIX"/drive_c/windows/system32/
 }
