wisotool2: Added Torchlight, debugged.  It can now install games from dvd, and obeys the -s / --save_isos flag.

diff --git a/trunk/wisotool2 b/trunk/wisotool2
--- a/trunk/wisotool2
+++ b/trunk/wisotool2
@@ -78,6 +78,44 @@ w_try()
     fi
 }
 
+w_try_regedit()
+{
+    # on windows, doesn't work without cmd /c
+    case "$OS" in
+    "Windows_NT") cmdc="cmd /c";;
+    *) unset cmdc
+    esac
+
+    w_try wisotool_early_wine $cmdc regedit "$@"
+}
+
+w_try_winetricks()
+{
+    w_try "$WISOTOOL_WINETRICKS" -q $*
+}
+
+w_read_game_key()
+{
+    _W_keyfile="$W_CACHE/$W_PACKAGE/key.txt"
+    if ! test -f "$_W_keyfile"
+    then
+        # read key from user
+        _W_keymsg="Enter the disc key for $W_PACKAGE"
+        case $WISOTOOL_MENU in
+        *zenity) W_KEY=`zenity --entry --text "$_W_keymsg"` ;;
+        *kdialog) W_KEY=`kdialog --inputbox "$_W_keymsg"` ;; 
+        *xmessage) w_die "sorry, can't read key from gui with xmessage" ;;
+        esac
+        if test "$W_KEY" = ""
+        then
+            w_die "No key given"
+        fi
+        echo "$W_KEY" > "$_W_keyfile"
+    fi
+    W_KEY=`cat "$_W_keyfile" | tr -d -`
+    unset _W_keyfile _W_keymsg
+}
+
 # Convert a Unix path to a Windows path
 # Usage is lowest common denominator of cygpath/winepath
 # so -u to convert to unix, and -w to convert to windows
@@ -102,7 +140,7 @@ w_verify_sha1sum()
     _W_vs_gotsum=`$SHA1SUM < $_W_file | sed 's/ .*//'`
     if [ "$_W_vs_gotsum"x != "$_W_wantsum"x ]
     then
-       die "sha1sum mismatch!  Rename $_W_vs_file and try again."
+       w_die "sha1sum mismatch!  Rename $_W_vs_file and try again."
     fi
     unset _W_vs_wantsum _W_vs_file _W_vs_gotsum
 }
@@ -206,11 +244,11 @@ w_mount()
     else
         case "$WISOTOOL_OPT_SAVE" in
         0)
-            wisotool_cache_iso "$1" 
-            wisotool_mount_cached_iso "$1" 
+            wisotool_mount_real_volume "$1"
             ;;
         1)
-            wisotool_mount_real_volume "$1"
+            wisotool_cache_iso "$1" 
+            wisotool_mount_cached_iso "$1" 
             ;;
         esac
     fi
@@ -227,16 +265,53 @@ w_umount()
         gksudo)
           # -l lazy unmount in case executable still running
           $WISOTOOL_SUDO "umount -l $WISOTOOL_ISO_MOUNT_ROOT"
-          try $WISOTOOL_SUDO "rm -rf $WISOTOOL_ISO_MOUNT_ROOT"
+          w_try $WISOTOOL_SUDO "rm -rf $WISOTOOL_ISO_MOUNT_ROOT"
           ;;
         *)
           $WISOTOOL_SUDO umount -l $WISOTOOL_ISO_MOUNT_ROOT
-          try $WISOTOOL_SUDO rm -rf $WISOTOOL_ISO_MOUNT_ROOT
+          w_try $WISOTOOL_SUDO rm -rf $WISOTOOL_ISO_MOUNT_ROOT
           ;;
         esac
-        rm -f "$WINEPREFIX"/dosdevices/${WISOTOOL_ISO_MOUNT_LETTER}:
-        rm -f "$WINEPREFIX"/dosdevices/${WISOTOOL_ISO_MOUNT_LETTER}::
+        rm -f "$WINEPREFIX"/dosdevices/${W_ISO_MOUNT_LETTER}:
+        rm -f "$WINEPREFIX"/dosdevices/${W_ISO_MOUNT_LETTER}::
     fi
+}
+
+w_ahk_do() {
+   load_autohotkey
+   _W_CR=`printf \\\\r`
+   echo "$@" | sed "s/\$/$CR/" > "$W_TMP"/tmp.ahk
+   $WINE "$W_PROGRAMS_X86_UNIX/AutoHotkey/AutoHotkey.exe" "$W_TMP_WIN"\\tmp.ahk
+   unset _W_CR
+}
+
+load_autohotkey()
+{
+    test -f "$W_PROGRAMS_X86_UNIX/AutoHotkey/AutoHotkey.exe" || w_try_winetricks autohotkey
+}
+
+# Usage: workaround_wine_bug bugnumber [good-wineversion-shell-pattern]
+# False (nonzero status) on Windows.
+# True (zero status) on Wine unless good-wineversion-shell-pattern is set
+# and matches the current wine version.
+# For debugging: if you want to skip a bug's workaround, put the bug number in the
+# environment variable WISOTOOL_BLACKLIST to disable it.
+w_workaround_wine_bug()
+{
+    if test "$WINE" = ""
+    then
+        echo No need to work around wine bug $1 on windows
+        return 1
+    fi
+    # FIXME: accept wine version number as $2, only apply if before that
+    case $1 in
+    "$WISOTOOL_BLACKLIST")
+        echo wine bug $1 workaround blacklisted, skipping
+        return 1
+        ;;
+    esac
+    w_warn Working around wine bug $1
+    return 0
 }
 
 # Function for verbs to register themselves so they show up in the menu.
@@ -252,6 +327,7 @@ w_metadata()
 {
    file="$WISOTOOL_METADATA/$1.vars"
    shift
+   # FIXME: fall back to posix shell string manipulation if perl not present?
    perl -e 'for (@ARGV) { if (/(\w*)=(.*)/) { print "$1=\"$2\"\n"; } else { die "bad parameter $_" } }' "$@" > "$file"
 }
 
@@ -260,13 +336,14 @@ w_metadata()
 #   w_register_exe "$W_PROGRAMS_X86_WIN\\WorldOfGooDemo" WorldOfGoo.exe
 w_register_exe()
 {
-    _dir="$1"
-    _exe="$2"
+    _W_dir="$1"
+    _W_exe="$2"
     cat > "$W_DRIVE_C/run-$W_PACKAGE.bat" <<__EOF__
 ${W_PROGRAMS_DRIVE}:
-cd "_$dir"
-$_exe
+cd "$_W_dir"
+$_W_exe
 __EOF__
+    unset _W_dir _W_exe
 }
 
 #---- Private Functions ----
@@ -465,7 +542,7 @@ wisotool_cache_iso()
     case $WISOTOOL_OPT_DD in
     dd)
       dd if=$WISOTOOL_DEV of="$W_CACHE"/temp.iso bs=2048 conv=noerror,sync &
-      pid=$!
+      WISOTOOL_DD_PID=$!
       ;;
     ddrescue)
       if test "`which ddrescue`" = ""
@@ -473,17 +550,17 @@ wisotool_cache_iso()
           w_die "Please install ddrescue first."
       fi
       ddrescue -v -b 2048 $WISOTOOL_DEV "$W_CACHE"/temp.iso &
-      pid=$!
+      WISOTOOL_DD_PID=$!
       ;;
     esac
 
     # Note: if user presses ^C, wisotool_cleanup will call wisotool_iso_cleanup
-    while ps -p $pid > /dev/null 2>&1
+    while ps -p $WISOTOOL_DD_PID > /dev/null 2>&1
     do
       sleep 5
       ls -l "$W_CACHE"/temp.iso
     done
-    pid=""
+    unset WISOTOOL_DD_PID
 
     mv "$W_CACHE"/temp.iso "$WISOTOOL_IMG"
 
@@ -501,22 +578,24 @@ wisotool_mount_cached_iso()
     else
         # Linux
         # FIXME: find a way to mount or copy from image without sudo
+        _W_USERID=`id -u`
         case "$WISOTOOL_SUDO" in
         gksudo)
           w_try $WISOTOOL_SUDO "mkdir -p $WISOTOOL_ISO_MOUNT_ROOT"
-          w_try $WISOTOOL_SUDO "mount -o ro,loop,uid=$USERID,unhide $WISOTOOL_IMG $WISOTOOL_ISO_MOUNT_ROOT"
+          w_try $WISOTOOL_SUDO "mount -o ro,loop,uid=$_W_USERID,unhide $WISOTOOL_IMG $WISOTOOL_ISO_MOUNT_ROOT"
           ;;
         *)
           w_try $WISOTOOL_SUDO mkdir -p $WISOTOOL_ISO_MOUNT_ROOT
-          w_try $WISOTOOL_SUDO mount -o ro,loop,uid=$USERID,unhide "$WISOTOOL_IMG" $WISOTOOL_ISO_MOUNT_ROOT
+          w_try $WISOTOOL_SUDO mount -o ro,loop,uid=$_W_USERID,unhide "$WISOTOOL_IMG" $WISOTOOL_ISO_MOUNT_ROOT
           ;;
         esac
 
-        echo "Mounting as drive ${WISOTOOL_ISO_MOUNT_LETTER}:"
+        echo "Mounting as drive ${W_ISO_MOUNT_LETTER}:"
         # Gotta provide a symlink to the raw disc, else installers that check volume names will fail
-        rm -f "$WINEPREFIX/dosdevices/${WISOTOOL_ISO_MOUNT_LETTER}:"*
-        ln -sf "$WISOTOOL_IMG" "$WINEPREFIX/dosdevices/${WISOTOOL_ISO_MOUNT_LETTER}::"
-        ln -sf "$WISOTOOL_ISO_MOUNT_ROOT" "$WINEPREFIX/dosdevices/${WISOTOOL_ISO_MOUNT_LETTER}:"
+        rm -f "$WINEPREFIX/dosdevices/${W_ISO_MOUNT_LETTER}:"*
+        ln -sf "$WISOTOOL_IMG" "$WINEPREFIX/dosdevices/${W_ISO_MOUNT_LETTER}::"
+        ln -sf "$WISOTOOL_ISO_MOUNT_ROOT" "$WINEPREFIX/dosdevices/${W_ISO_MOUNT_LETTER}:"
+        unset _W_USERID
     fi
 }
 
@@ -525,7 +604,7 @@ wisotool_mount_real_volume()
     # Wait for user to insert disc.  
     # For now, only support distros that automount
 
-    warn "Please insert volume $1"
+    _W_mountmsg="Please insert and mount volume '$1' (needed for app '$W_PACKAGE')"
 
     if test "$WINE" = ""
     then
@@ -533,6 +612,7 @@ wisotool_mount_real_volume()
     else
         while ! test -d "/media/$1"
         do
+            w_warn "$_W_mountmsg"
             ls /media
             sleep 1
         done
@@ -540,24 +620,31 @@ wisotool_mount_real_volume()
         wisotool_detect_optical_drive
 
         # Gotta provide a symlink to the raw disc, else installers that check volume names will fail
-        rm -f "$WINEPREFIX/dosdevices/${WISOTOOL_ISO_MOUNT_LETTER}:"*
-        ln -sf "$WISOTOOL_DEV" "$WINEPREFIX/dosdevices/${WISOTOOL_ISO_MOUNT_LETTER}::"
-        ln -sf "/media/$1" "$WINEPREFIX/dosdevices/${WISOTOOL_ISO_MOUNT_LETTER}:"
+        rm -f "$WINEPREFIX/dosdevices/${W_ISO_MOUNT_LETTER}:"*
+        ln -sf "$WISOTOOL_DEV" "$WINEPREFIX/dosdevices/${W_ISO_MOUNT_LETTER}::"
+        ln -sf "/media/$1" "$WINEPREFIX/dosdevices/${W_ISO_MOUNT_LETTER}:"
     fi
 
     # FIXME: need to remount some discs with unhide option, 
     # add that as option to w_mount
+
+    unset _W_mountmsg
 }
 
 wisotool_cleanup()
 {
-    echo "Caught signal, cleaning up."
-    case "$pid" in
-    "") ;;
-    *) kill $pid ;;
-    esac
     test "$W_CACHE_SYMLINK" && rm -f "$W_CACHE_SYMLINK"
     rm -rf "$WISOTOOL_WORKDIR"
+}
+
+wisotool_kill_handler()
+{
+    echo "Caught signal, cleaning up."
+    case "$WISOTOOL_DD_PID" in
+    "") ;;
+    *) kill $WISOTOOL_DD_PID ;;
+    esac
+    wisotool_cleanup
     echo "Done cleanup, quitting."
     exit 1
 }
@@ -575,7 +662,7 @@ wisotool_init()
     mkdir -p "$WISOTOOL_METADATA"
 
     # Delete work directory after each run
-    trap wisotool_cleanup 1 2 3 6
+    trap wisotool_kill_handler 1 2 3 6
 
     # Which GUI helper to use (none/zenity/kdialog).  See wisotool_detect_gui.
     WISOTOOL_MENU=none
@@ -584,11 +671,11 @@ wisotool_init()
 
     # Overridden for windows
     WISOTOOL_ISO_MOUNT_ROOT=/mnt/wisotool
-    WISOTOOL_ISO_MOUNT_LETTER=i
+    W_ISO_MOUNT_LETTER=i
 
     # Whether to always cache cached iso's (1) or only use cache if present (0)
     # Can be inherited from environment or set via -c, defaults to off
-    WISOTOOL_OPT_SAVE=${WISOTOOL_SAVE_ISO:-0}
+    WISOTOOL_OPT_SAVE=${WISOTOOL_OPT_SAVE:-0}
 
     # what program to use to make disc image (dd or ddrescue)
     WISOTOOL_OPT_DD=${WISOTOOL_OPT_DD:-dd}
@@ -607,12 +694,12 @@ wisotool_init()
         W_DRIVE_C="$WINEPREFIX/dosdevices/c:"
         ;;
     esac
-
-    # Verbs can rely on W_TMP being empty at entry, and deleted after return
-    W_TMP="$WISOTOOL_WORKDIR/tmp"
-    W_TMP_WIN="`w_pathconv -w "$WISOTOOL_TMP"`"
+    # Verbs can rely on W_TMP being empty at entry, deleted after return, and a subdir of C:
+    W_TMP="$W_DRIVE_C/windows/temp"
+    W_TMP_WIN="C:\\windows\\temp"
 
     # Where application installers are cached
+    # FIXME: move those tr's and sed's into w_pathconv, if they're still needed?
     W_CACHE="${W_CACHE:-$WISOTOOL_DIR/cache}"
     W_CACHE_WIN="`w_pathconv -w $W_CACHE | tr '\012' ' ' | sed 's/ $//'`"
 
@@ -622,6 +709,7 @@ wisotool_init()
     "") w_die "$WINE cmd.exe /c echo '%ProgramFiles%' returned empty string" ;;
     %*) w_die "$WINE cmd.exe /c echo '%ProgramFiles%' returned unexpanded string... do you own the parent of $WINEPREFIX ?" ;;
     esac
+    # FIXME: move that tr into w_pathconv, if it's still needed?
     W_PROGRAMS_UNIX="`w_pathconv -u "$W_PROGRAMS_WIN" | tr -d '\015' `"
 
     # 64 bit windows has a second directory for program files
@@ -638,6 +726,14 @@ wisotool_init()
 
     # Whether to automate installs (0=no, 1=yes)
     W_OPT_UNATTENDED={$W_OPT_UNATTENDED:-0}
+
+    WISOTOOL_WINETRICKS="$WISOTOOL_SRCDIR/winetricks"
+    if ! test -f "$WISOTOOL_WINETRICKS"
+    then
+        WISOTOOL_WINETRICKS="$WISOTOOL_CACHE/winetricks/winetricks"
+        W_PACKAGE=winetricks w_download http://kegel.com/wine/winetricks
+    fi
+
 }
 
 wisotool_usage()
@@ -674,6 +770,9 @@ wisotool_handle_option()
 # Must initialize variables before calling w_metadata
 if ! test "$WISOTOOL_LIB"
 then
+    WISOTOOL_SRCDIR=`dirname $0`
+    WISOTOOL_SRCDIR=`cd $WISOTOOL_SRCDIR; /bin/pwd`
+
     # Handle options before init, to avoid starting wine for --help or --version
     while wisotool_handle_option $1
     do
@@ -701,12 +800,88 @@ load_blobby_volley()
     mkdir -p "$W_DRIVE_C/BlobbyVolley"
     cd "$W_CACHE/$W_PACKAGE"
     w_try unzip blobby.zip -d "$W_DRIVE_C/BlobbyVolley"
-    w_declare_exe "c:\\BlobbyVolley" "volley.exe"
+    w_register_exe "c:\\BlobbyVolley" "volley.exe"
 
-    if workaround_wine_bug 4432
+    if w_workaround_wine_bug 4432
     then
-        warn "Go bug Wolfgang Sang for the bugfix :-)"
+        w_warn "You may need to apply a patch, see http://bugs.winehq.org/show_bug.cgi?id=4432#c15"
     fi
+}
+
+#----------------------------------------------------------------
+
+w_metadata singularity \
+    title=Singularity \
+    publisher=Activision \
+    year=2010 \
+    media=dvd \
+    file1=SNG_DVD.iso
+
+load_singularity()
+{
+    w_read_game_key
+    w_mount SNG_DVD
+    w_ahk_do "
+        run ${W_ISO_MOUNT_LETTER}:setup.exe
+        winwait, Activision(R) - InstallShield, Select the language for the installation from the choices below.
+        sleep 1000
+        controlclick, Button1, Activision(R) - InstallShield, Select the language for the installation from the choices below.
+        sleep 1000
+        winwait, Singularity(TM), Keycode Check
+        sleep 1000
+        Send $W_KEY
+        sleep 1000
+        Send {Enter}
+        ; Well this is annoying...
+        Winwait, Keycode Check, The Keycode you entered appears to be valid.
+        sleep 1000
+        Send {Enter}
+        winwait, Singularity(TM), The InstallShield Wizard will install Singularity(TM) on your computer
+        sleep 1000
+        controlclick, Button1, Singularity(TM), The InstallShield Wizard will install Singularity(TM) on your computer
+        winwait, Singularity(TM), Please read the following license agreement carefully
+        sleep 1000
+        controlclick, Button5, Singularity(TM), Please read the following license agreement carefully
+        sleep 1000
+        controlclick, Button2, Singularity(TM), Please read the following license agreement carefully
+        winwait, Singularity(TM), Minimum System Requirements
+        sleep 1000
+        controlclick, Button1, Singularity(TM), Minimum System Requirements
+        winwait, Singularity(TM), Select the setup type to install
+        controlclick, Button4, Singularity(TM), Select the setup type to install
+        sleep 5000
+        Loop
+        {
+            ifwinexist, Singularity(TM)
+                sleep 15000
+            else
+                break
+        }
+        "
+
+    if w_workaround_wine_bug 6971
+    then
+        w_try_winetricks mwo=force
+    fi
+
+    if w_workaround_wine_bug 22548
+    then
+        echo "Disabling \'depth of field\'"
+        cat > "$W_TMP"/dof.reg <<_EOF_
+REGEDIT4
+
+[HKEY_CURRENT_USER\Software\Activision\Singularity]
+"DepthOfField"=dword:00000000
+
+_EOF_
+        w_try_regedit "$W_TMP_WIN"\\dof.reg
+    fi
+
+    w_register_exe "$W_PROGRAMS_X86_WIN\\Activision\\Singularity(TM)\\Binaries" "Singularity.exe"
+
+    # Clean up crap left over in c:\ when the installer runs the vc 2008 redistributable installer
+    cd "$W_DRIVE_C"
+    rm -f VC_RED.* eula.*.txt globdata.ini install.exe install.ini install.res.*.dll vcredist.bmp
 }
 
 #----------------------------------------------------------------
@@ -722,7 +897,7 @@ load_torchlight() {
     w_mount "Torchlight"
     w_ahk_do "
         SetTitleMatchMode, 2
-        Run, ${WISOTOOL_ISO_MOUNT_LETTER}:Torchlight.exe
+        Run, ${W_ISO_MOUNT_LETTER}:Torchlight.exe
         WinWait, Torchlight Setup, This wizard will guide
         sleep 1000
         ControlClick, Button2, Torchlight Setup, This wizard will guide
@@ -802,6 +977,7 @@ done
 
 if ! test "$WISOTOOL_LIB"
 then
+    wisotool_detect_sudo
     # If no non-option arguments given, read them from GUI
     case "$1" in
     "")
@@ -812,6 +988,8 @@ then
 
     for W_PACKAGE in $*
     do
+        w_try mkdir -p "$W_TMP"
+
         case $W_PACKAGE in
 
         # External verbs
@@ -842,6 +1020,8 @@ then
             chmod +x "$postfile"
             ( . "$postfile" )
         fi
+
+        rm -rf "$W_TMP"
 
     done
 
